### PR TITLE
Add -writes option to set number of disc writes in ssd catalogue

### PR DESCRIPTION
**Pull request by ZornsLemma**
As discussed in https://github.com/stardot/beebasm/issues/39. Do we need to tweak the validation before merging?

(github shows this can't be automatically merged, although I suspect it's not a difficult issue to resolve.)

### CODE REVIEW

**Comment by chriskillpack** [comment]
Can you give me an example where this feature would be used?

LGTM but I don't have write access to this repo.

**Comment by ZornsLemma** [comment]
D'oh! I was merging this and it looks like it's already on proposed-updates and I just hadn't noted that on #39, hence (more or less) the conflicts.

I think the motivation here is that it allows the user control over the generated disc image - when you do *CAT on a DFS disc, it shows the write count in brackets after the disc title. I don't specifically know how tricky (the originator of this code) uses it, but I can think of two possible benefits:
- It makes the disc look more "realistic", if you were actually creating it with DFS it would be unlikely (if possible) that the write count is 0
- It provides a cheap way of allowing different versions of a disc image to be distinguished.

**Comment by chriskillpack** [comment]
I see -writes commits on proposed-updates, so I think we can close this PR?

Thanks for the example.

**Comment by ZornsLemma** [comment]
Yes, I think we can. Cheers.

**Pull request closed without merging**
