### PR TITLE
Insist on a space after a mnemonic with -w

### PR DESCRIPTION
**Pull request by Homo-carbonis**
I'm not that good with git but I think I managed to do the rebase properly this time. The update to streampos is now gone.

### CODE REVIEW

**Comment by mungre** [comment]
Thank you, that looks good.

(Discussed in #80)

**Comment by chriskillpack** [comment]
@mungre merge this if you think this should go into v1.10.

**Comment by mungre** [comment]
I'm not sure about this one for v1.10.  It is a good idea but it's also a breaking change potentially.

@ZornsLemma what do you think?

**Comment by ZornsLemma** [comment]
I agree, it's probably best to keep this out of 1.10. It is a good idea (assuming there isn't a lurking gotcha where calculated values that "should" fail in practice start to work because they generate a negative value) but there's a fair risk of breaking something, and this is a long-standing behaviour so I don't think we should rush to change it with a release so close.

**Comment by mungre** [comment]
I merged this into master manually since we're no longer using proposed-updates.

**Pull request closed without merging**
